images:
  mysql:
    repository: ranchercharts/mysql
    tag: 5.7.14

config:
  clusterProvider: infrastructure
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  mysql:
    baseUrl: ''
    hostname: ''
  useDefaultImages: 'True'
  mySqlDatabase: 'admin'
  mySqlUsername: 'admin'
  mySqlPassword: 'secret'
  mySqlNodePortNumber: '3306'
  enableMySqlMetrics: 'False'

service:
  mysql:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: ''

ingress:
  mysql:
    certificate: ''
    enabled: false
    hostname: ''
    path: /
    tls: false
    issuer:
      name: letsencrypt-staging

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 1Gi
  storageClass: ''
  velero:
    enabled: false
  stash:
    bucket: ''
    container: ''
    enabled: false
    endpoint: s3.amazonaws.com
    keepLast: 30
    paused: false
    prefix: stash
    schedule: '0 0 * * *'
    secret: stash-config-stash-config
    type: s3
    restore:
      snapshot:
        data: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
