apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql.fullname" . }}-busybox
  labels:
    app: {{ template "mysql.name" . }}-busybox
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: container
  selector:
    app: {{ template "mysql.name" . }}-busybox
    release: {{ .Release.Name }}
